### ISSUE TITLE
problems to this helper

### ISSUE THREAD

**Issue by sxx-sxx** [WCY-dt/SEU-NewCourseElection-Helper#1]
First of all, I'm very gratful to you for this helper. This can help a lot and reallly deserves a star！
But I have a small question about this code. When I run the helper.exe，it would quit unexpectedly, this puzzles me a lot. Can you help me to solve this question？
Thanks a lot!

**Comment by WCY-dt** [comment]
Thanks a lot for your feedback.
If it happens before login, please tell me how to reappear it. 
If it happens after login, this problem could be caused by wrong input (but I don't want to fix it)

**Comment by sxx-sxx** [comment]
It happens before login,and it cannot reappear until I open again.
And then it will quit again……

**Comment by WCY-dt** [comment]
> It happens before login

I use pyinstaller to generate the .exe file.
Could you compile and run the .py file and tell me whether it will crash again?

**Comment by sxx-sxx** [comment]
OK, I will try it.
