### ISSUE TITLE
好像运行不起来，，，是用py3的环境运行吗？

### ISSUE THREAD

**Issue by 04019226** [WCY-dt/SEU-NewCourseElection-Helper#2]
好像运行不起来，，，是用py3的环境运行吗？

**Comment by WCY-dt** [comment]
我找到问题了，是因为chrome driver没有打包到exe中，因此缺少运行的必要组件。
我手头上忙完了来改一下

**Comment by WCY-dt** [comment]
如果你直接跑源文件的话，需要把chrome driver下载后放到python安装目录里

**Comment by 04019226** [comment]
感谢大佬orz

**Comment by WCY-dt** [comment]
> 感谢大佬orz

我太菜了嘤嘤嘤
