### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by vegedoge** [WCY-dt/SEU-NewCourseElection-Helper#3]
Hello！同学你好！我在线运行程序没反应...尝试下载了你的源码本地运行，但是出了点问题，不知道是不是版本不一致( ´▽` )
我用的python 3.7 --selenium 4.2.0

所以做了一些修改，如果有人遇到类似问题可以参考

1. 关于Login失败，需要先在webdriver处给出chrome启动器的本地地址，然后绑定python和chrome启动器，有关方式，可以百度/谷歌selenium+chrome有详细教程，很简单。

2.关于find_element_by_xpath，我的编译器提示需要升级（版本？），然后一律改成了find_element(by=By.XPATH,value=...）格式，我测试可以正常运行。不过在使用by之后需要再import By，也就是from selenium.webdriver.common.by import By。
 
3. 环境变量。源代码好像是使用环境变量来赋值username等个人信息，可能是为了online运行？我不会github的online怎么搞orz
所以这里我简化了一下直接采用字符串手输。

4. 在遍历课程(class_list)和遍历老师(teacher_list)时，find_element改为find_elements，避免出现for循环提示无法迭代的问题。

5. 在选择页面(pages)时，需要选择当前页面(number active)，源代码的value=’number active‘我跑会抛异常...在修改格式后，我把这里一并改为value='//*[@Class="number active"]'的xpath表达式就好了。

6. 有个问题很好奇？
源代码对于同一个while循环做了很多次重复，我没太看懂这个的意义orz 试了试f8单步执行感觉并没有用到后面的while，所以上面提到的修改除了第一个while我都没动，目前测试结果不影响正常使用。秉着能动就别管的原则，我把它们都保留了没改hhhhhh

另外我把修改后的代码做了个branch传到我fork走的库里面了，应该可以下载？没在代码里加什么注释，感觉原来的变量命名就挺好懂的，就只做了些修改。

7. 最后感谢大佬开源（代码风格我好喜欢）。
本人前端没咋学过，全是面向demo编程⊙﹏⊙∥，要是上述修改有不合适的地方还望指出orz

**Comment by WCY-dt** [comment]
同学你好，感谢。
这份代码最早是我随手写了自己用的，所以代码会比较乱，各种操作也尽量用写起来方便的方法实现（指不用request、各种无意义的代码满天飞∠( ᐛ 」∠)＿）。放到GitHub上后，发现有人fork，就加了GitHub actions方便使用。
选课系统每学期都会更新，所以每学期都会冒出一些bug。之前都给改了，但我这学期实在有点忙，没来得及修改。
如果你愿意，可否将你修改的内容提交一个pr？(>^ω^<)

**Comment by vegedoge** [comment]
okk. 那我等下就pull request  ( •̀ ω •́ )y
